# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('mix_type', models.CharField(choices=[('copy', 'copy'), ('value', 'value'), ('choice', 'choice'), ('shuffle', 'shuffle')], default='copy', max_length=64)),
                ('mix_setting', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='fieldsetting',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_db_mixer.ModelSetting'),
        ),
    ]
